name: Debug Environment Variablesw #  Correct: Top-level mapping
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Debug user secret variable #  Dashes are only expected here (nested list)
        run: |
          echo "User is: ${{ vars.SNOWFLAKE_USER }}"

